# Server设置
[server]
    Address    = ":8888"

[database]
    [[database.default]]
            host         = "39.105.69.149"
            port         = "3306"
            user         = "root"
            pass         = "zskj123456"
            name         = "rat"
            type         = "mysql"

[user]
    [jwt]
        hours = 72
        secret = "rat"